-- Groups table
CREATE TABLE groups
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description TEXT,
    owner_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

-- Group members table
CREATE TABLE group_members
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id  BIGINT                                  NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    joined_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id),
    CONSTRAINT uc_group_members_group_user UNIQUE (group_id, user_id)
);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- Group member permissions (element collection)
CREATE TABLE group_member_permissions
(
    group_member_id BIGINT       NOT NULL,
    permission      VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_group_member_permissions PRIMARY KEY (group_member_id, permission)
);

ALTER TABLE group_member_permissions
    ADD CONSTRAINT FK_PERMISSIONS_ON_GROUP_MEMBER FOREIGN KEY (group_member_id) REFERENCES group_members (id);

-- Group invitations table
CREATE TABLE group_invitations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id    BIGINT                                  NOT NULL,
    inviter_id  BIGINT                                  NOT NULL,
    invitee_id  BIGINT                                  NOT NULL,
    status      VARCHAR(20)                             NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_group_invitations PRIMARY KEY (id)
);

ALTER TABLE group_invitations
    ADD CONSTRAINT FK_INVITATIONS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_invitations
    ADD CONSTRAINT FK_INVITATIONS_ON_INVITER FOREIGN KEY (inviter_id) REFERENCES users (id);

ALTER TABLE group_invitations
    ADD CONSTRAINT FK_INVITATIONS_ON_INVITEE FOREIGN KEY (invitee_id) REFERENCES users (id);

-- Alter tasks: add group_id and assignee_id (nullable)
ALTER TABLE tasks
    ADD COLUMN group_id BIGINT;

ALTER TABLE tasks
    ADD COLUMN assignee_id BIGINT;

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES users (id);
